#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 16 13:19:57 2017

@author: michaeloboyle
"""
from github import Github
import jsonpickle

file_name = 'test_git_API'
userKey = 'fd6142ee42ac9db47a64c0848982f5b21ee68221' 
git = Github('fd6142ee42ac9db47a64c0848982f5b21ee68221')
user = git.get_user('oboyle-mikey')
repo = user.get_repo('software-engineering')

with open(file_name, 'w') as F:
     F.write(jsonpickle.encode(repo))

