#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 26 16:16:30 2017

@author: michaeloboyle
"""

from github import Github
import jsonpickle

file_name = 'user1'
userKey = 'ad3cde5c3202a823a8b921d65ac8022599b1532f'
git = Github(userKey)
user = git.get_user('oboyle-mikey')


with open(file_name, 'w') as F:
     F.write(jsonpickle.encode(user))